const $=id=>document.getElementById(id);let tabId,state;
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
async function send(type,payload={}){return chrome.runtime.sendMessage({type,...payload})}
function setStatus(title,tone,summary,badge){$('statusTitle').textContent=title;$('statusTitle').className='statusTitle '+(tone||'');$('statusSummary').textContent=summary;$('statusBadge').textContent=badge||title;$('statusBadge').className='statusBadge '+(tone||'')}
function setRing(score,level){const deg=Math.max(0,Math.min(100,Number(score)||0))*3.6;$('scoreRing').style.background=`conic-gradient(var(--gold) 0deg,var(--gold) ${deg}deg,rgba(255,255,255,.065) ${deg}deg)`;$('riskLabel').textContent=level?level+' RISK':'NO RISK';$('riskLabel').className=`riskLabel ${(level||'').toLowerCase()}`}
function render(s){state=s;const fp=s?.fingerprint,result=s?.result||{},level=String(result.level||'').toLowerCase();$('origin').textContent=fp?.site?.origin||'This page cannot be monitored';
if(s?.status==='PAUSED')setStatus('MONITORING PAUSED','paused','Resume monitoring to compare this page with its baseline.','PAUSED');
else if(s?.status==='UNMONITORED')setStatus('NOT MONITORED','warning','Create a baseline to begin semantic change detection.','SETUP');
else if(s?.status==='IGNORED')setStatus('CHANGE IGNORED','warning','This change is suppressed for the current session; the baseline was not rewritten.','IGNORED');
else if(s?.status==='CHANGES_DETECTED')setStatus('CHANGES DETECTED','danger','Security-relevant page semantics differ from the saved baseline.','ACTION NEEDED');
else if(s?.status==='TRUSTED')setStatus('TRUSTED','trusted','The current page matches the active baseline.','PROTECTED');
else setStatus('UNAVAILABLE','','Open a normal http or https page to use PageDNA.','UNAVAILABLE');
if(fp){$('scoreCard').classList.remove('hidden');$('metrics').classList.remove('hidden');$('match').textContent=`${result.matchPercent??0}%`;$('score').textContent=`${result.score??0}/100`;$('scripts').textContent=fp.metrics?.scriptCount??0;$('origins').textContent=fp.metrics?.externalOriginCount??0;$('frames').textContent=fp.metrics?.frameCount??0;$('forms').textContent=fp.metrics?.sensitiveFormCount??0;setRing(result.score,level)}
const changes=result.changes||[];$('evidenceCount').textContent=changes.length;
if(changes.length){$('changesCard').classList.remove('hidden');$('changes').innerHTML=changes.map(c=>`<li><span class="changeLabel">${esc(c.label)}</span><span class="changeValue">${esc(c.oldValue)} → ${esc(c.newValue)}</span><span class="changeWhy">${esc(c.why)}</span></li>`).join('')}else $('changesCard').classList.add('hidden');
const next=$('nextStep');next.classList.add('hidden');if(s?.status==='TRUSTED'){next.classList.remove('hidden');$('nextTitle').textContent='Baseline healthy';$('nextText').textContent='PageDNA found no security-relevant semantic drift.'}else if(s?.status==='CHANGES_DETECTED'){next.classList.remove('hidden');$('nextTitle').textContent='Review before trusting';$('nextText').textContent='Inspect the evidence, then decide whether the change is expected.'}
const actions=$('actions');actions.innerHTML='';const button=(text,cls,fn)=>{const b=document.createElement('button');b.textContent=text;b.className='btn '+cls;b.onclick=fn;actions.appendChild(b)};
if(s?.status==='UNMONITORED'&&fp)button('CREATE BASELINE','primary',()=>act('PD_CREATE_BASELINE'));
if(s?.status==='CHANGES_DETECTED'||s?.status==='IGNORED'){button('INVESTIGATE','secondary',showInvestigation);button('TRUST THIS CHANGE','primary',()=>act('PD_TRUST_CHANGE'));button('IGNORE ONCE','dangerBtn',()=>act('PD_IGNORE_ONCE',{origin:fp.site.origin}))}
if(!fp&&s?.status==='UNAVAILABLE')button('GRANT SITE ACCESS','primary',async()=>{try{const tab=await chrome.tabs.get(tabId);if(tab.url?.startsWith('file://')){alert('Open chrome://extensions → PageDNA → enable Allow access to file URLs, then reload.');return}const origin=new URL(tab.url).origin;const granted=await chrome.permissions.request({origins:[`${origin}/*`]});if(granted)location.reload();else alert('Site access was not granted.')}catch(e){alert(e.message||'Unable to request site access.')}})}
async function act(type,payload={}){const r=await send(type,{tabId,fingerprint:state?.fingerprint,...payload});if(r?.ok)render((await send('PD_GET_TAB_STATE',{tabId})).state);else alert(r?.error||'Action failed')}
function showInvestigation(){const c=state?.result?.changes||[];alert(c.map(x=>`${x.label}\nOLD: ${x.oldValue}\nNEW: ${x.newValue}\nWHY: ${x.why}`).join('\n\n')||'No changes recorded.')}
async function init(){const tabs=await chrome.tabs.query({active:true,currentWindow:true});tabId=tabs[0]?.id;const r=await send('PD_GET_TAB_STATE',{tabId});render(r.state);const settings=await send('PD_GET_SETTINGS');const paused=!!settings.settings?.paused;$('pauseBtn').classList.toggle('active',paused);$('monitorState').classList.toggle('paused',paused);$('monitorState').innerHTML=`<i></i> ${paused?'PAUSED':'LIVE'}`;$('pauseBtn').onclick=async()=>{await send('PD_SET_PAUSED',{paused:!paused});location.reload()}}
$('historyBtn').onclick=async()=>{const r=await send('PD_GET_HISTORY',{limit:20});alert((r.history||[]).map(x=>`${new Date(x.time).toLocaleString()} — ${x.level} — ${x.event}${x.score!=null?` (${x.score}/100)`:''}`).join('\n')||'No history yet.')};
$('optionsBtn').onclick=()=>chrome.runtime.openOptionsPage();init();